In [1]:
import numpy as np

In [3]:
arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.ndim

1

In [5]:
arr.shape

(5,)

In [6]:
arr.size

5

In [7]:
arr[0]

np.int64(1)

In [8]:
arr[1]

np.int64(2)

In [10]:
arr = np.array(([1,2,3],[5,6,7]))

In [11]:
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
arr = np.array(([10,20,30,40,50],[60,70,80,90,100],[11,12,13,14,15]))

In [13]:
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 11,  12,  13,  14,  15]])

In [14]:
arr[0]

array([10, 20, 30, 40, 50])

In [15]:
arr[1]

array([ 60,  70,  80,  90, 100])

In [16]:
arr[2]

array([11, 12, 13, 14, 15])

In [18]:
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 11,  12,  13,  14,  15]])

In [20]:
arr[0][1]

np.int64(20)

In [21]:
arr[0][1:]

array([20, 30, 40, 50])

In [22]:
arr.ndim

2

In [23]:
arr.shape

(3, 5)

In [24]:
arr.size

15

In [25]:
len(arr)

3

In [34]:
arr[0:1,2:4]

array([[30, 40]])

In [35]:
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 11,  12,  13,  14,  15]])

In [36]:
arr.mean

<function ndarray.mean(axis=None, dtype=None, out=None, **kwargs)>

In [37]:
print(arr.mean)

<built-in method mean of numpy.ndarray object at 0x0000029C765CE790>


In [38]:
arr.mean()

np.float64(41.0)

In [40]:
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 11,  12,  13,  14,  15]])

In [42]:
arr.min

<function ndarray.min(axis=None, out=None, **kwargs)>

In [43]:
print(arr.min)

<built-in method min of numpy.ndarray object at 0x0000029C765CE790>


In [44]:
arr.min()

np.int64(10)

In [45]:
arr.max()

np.int64(100)

In [46]:
arr.argmin()

np.int64(0)

In [48]:
arr.argmax()

np.int64(9)

In [49]:
arr.std()

np.float64(30.702877172451878)

In [50]:
arr.var()

np.float64(942.6666666666666)

In [53]:
print(dir(arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [54]:
arr.cumsum()

array([ 10,  30,  60, 100, 150, 210, 280, 360, 450, 550, 561, 573, 586,
       600, 615])

In [55]:
arr.cumprod()

array([                  10,                  200,                 6000,
                     240000,             12000000,            720000000,
                50400000000,        4032000000000,      362880000000000,
          36288000000000000,   399168000000000000,  4790016000000000000,
        6929975778871345152,  4785940535651074048, -1997868260072095744])

In [56]:
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 11,  12,  13,  14,  15]])

In [57]:
arr * 2

array([[ 20,  40,  60,  80, 100],
       [120, 140, 160, 180, 200],
       [ 22,  24,  26,  28,  30]])

In [58]:
arr - 20

array([[-10,   0,  10,  20,  30],
       [ 40,  50,  60,  70,  80],
       [ -9,  -8,  -7,  -6,  -5]])

In [59]:
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 11,  12,  13,  14,  15]])

In [64]:
arr = arr

In [65]:
arr = arr

In [69]:
arr

2

In [70]:
arr = np.array(([1,2,3,4,5,6,7,8,9,10]))

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [73]:
arr // 10

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [74]:
arr[4:8] = 1

In [75]:
arr

array([ 1,  2,  3,  4,  1,  1,  1,  1,  9, 10])